// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const config =  {
    API: {
        GraphQL: {
          endpoint: `https://${process.env.NEXT_PUBLIC_ENDPOINT}.appsync-api.ap-northeast-1.amazonaws.com/graphql`,
          region: 'ap-northeast-1',
          defaultAuthMode: 'apiKey',
          apiKey: process.env.NEXT_PUBLIC_API_KEY,
        }
    }
};

export default config;